version: "3.9"

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: agriconnect_db
      MYSQL_USER: thabang
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: django_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=agriconnect_db
      - DB_USER=thabang
      - DB_PASSWORD=12345

  simulate_sensors:
    build: .
    container_name: simulate_sensors
    command: python manage.py simulate_sensors
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=agriconnect_db
      - DB_USER=thabang
      - DB_PASSWORD=12345

  run_forecast:
    build: .
    container_name: run_forecast
    command: python manage.py run_forecast
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=agriconnect_db
      - DB_USER=thabang
      - DB_PASSWORD=12345

volumes:
  db_data:
